### ISSUE TITLE
Card Color doesnt take current theme into account

### ISSUE THREAD

**Issue by IrealiTY** [custom-components/sensor.nintendo_wishlist#13]
Maybe it's intended and I'm just not getting it :D But the card is always black no matter what skin is used.
![image](https://user-images.githubusercontent.com/1223686/88790134-fa6dfb00-d197-11ea-82df-6585a922a83e.png)

I had a look at the .js colour variables and they seem all correct in the skins I use. Is it intended to be black only?

PS: Using it with the Steam Wishlist Component

**Comment by boralyl** [comment]
I would not be surprised if I have it hardcoded to a dark theme, since that's what I personally use.  I'll take a look at how I might be able to setup this card properly to deal with themes.  I'm going to close this issue since it has to do with the card and not the component.  You can follow that issue here: https://github.com/custom-cards/nintendo-wishlist-card/issues/3

**Comment by boralyl** [comment]
FYI: this is fixed in the latest release: https://github.com/custom-cards/nintendo-wishlist-card/releases/tag/v2.1.0

```yaml
cards:
  - type: custom:nintendo-wishlist-card
    entity: sensor.nintendo_wishlist
    title: Switch Wishlist
    image_style: backgroundart
    max: 10
    accent_color: "#ff0000"
    title_color: "blue"
    line1_color: "yellow"
    line2_color: "purple"
    border_color: "#eaeaea"
```

Yields the following when using the default theme:

![image](https://user-images.githubusercontent.com/109865/88989881-8152ce80-d291-11ea-91c2-aa6a86c1b2d7.png)
