### ISSUE TITLE
Scan interval does not appear to work resulting in excessive updates.

### ISSUE THREAD

**Issue by boralyl** [custom-components/sensor.nintendo_wishlist#17]
**Describe the bug**
When the scan interval was set to 1 day, in less than 12 hours the update method was called 1700 times.

**Screenshots**
Example of turning the integration on:
![image](https://user-images.githubusercontent.com/109865/115042496-65777300-9e88-11eb-98ee-c5720f388782.png)
**Home Assistant Version:**
2021.4.2
**Additional context**
Configuration:

```yaml
nintendo_wishlist:
  scan_interval:
    # at least one of the following must be specified:
    days: 1
    hours: 0
    minutes: 0
    seconds: 0
    milliseconds: 0
  country: IT
  wishlist:
    - Pokémon Scudo
    - Picross
    - Yu-Gi-Oh
    - New Pokémon Snap
    - Super Mario Party
    - "Pokémon Let's Go, Pikachu!"
    - "The Legend of Zelda: Breath of the Wild"
    - Mario Kart 8 Deluxe
    - Brain Training
```
