### ISSUE TITLE
Idea to make more user friendly in the UI

### ISSUE THREAD

**Issue by fortepc** [custom-components/sensor.nintendo_wishlist#5]
# How it currently Works:
![image](https://user-images.githubusercontent.com/26149601/71670891-6d68dd80-2d3f-11ea-8dbc-233a2547cdef.png)
![image](https://user-images.githubusercontent.com/26149601/71670909-78bc0900-2d3f-11ea-99b0-37603cf6bd01.png)

# How I think it should work: 
![image](https://user-images.githubusercontent.com/26149601/71670971-ab660180-2d3f-11ea-90f9-65f20c396e5f.png)
![image](https://user-images.githubusercontent.com/26149601/71671122-20393b80-2d40-11ea-82cc-4dff1d25bd5f.png)

**Comment by fortepc** [comment]
Or maybe for the individual game sensors, do the current price as the 'value' of the sensor
![image](https://user-images.githubusercontent.com/26149601/71671203-655d6d80-2d40-11ea-9f2d-505729e506e2.png)

That way you can also track the price overtime to see how good of a deal you're actually getting. 

# (This would actually be my preferred way of this working)

**Comment by fortepc** [comment]
Or maybe change the sensor.game to binary_sensor.game and just make it the value of the sensor just be "on/off" and the extra details be attributes 
![image](https://user-images.githubusercontent.com/26149601/71671374-e9aff080-2d40-11ea-8858-cab005f7ede5.png)

**Comment by l111111l** [comment]
I would love to see that data too since whatever I do, I am not able to get a Wishlist custom Card to show :)

**Comment by boralyl** [comment]
Thanks for submitting an issue with some great mockups!  I agree that it would be much nicer if that information was easier to view and access.

The current value for the individual game sensors is the number of games on sale that match the search term.  If there is only a single match, then it could work exactly like you described above. 

However, if one of your search term sensors matches multiple games like this one then your idea will not work: 
![shantae](https://user-images.githubusercontent.com/109865/72199769-440e1880-33f5-11ea-9e5c-160b504dd378.png)

The state attributes look like this:

```yaml
on_sale:
  - box_art_url: >-
      https://www.nintendo.com/content/dam/noa/en_US/games/switch/s/shantae-half-genie-hero-ultimate-edition-switch/Switch_Shantae-HalfGenieHero-UltimateEdition_box.png
    normal_price: $29.99
    percent_off: 30
    sale_price: $20.99
    title: 'Shantae: Half-Genie Hero Ultimate Edition'
  - box_art_url: >-
      https://www.nintendo.com/content/dam/noa/en_US/games/switch/s/shantae-and-the-pirates-curse-switch/Switch_Shantae-PiratesCurse_box_eShop.png
    normal_price: $19.99
    percent_off: 40
    sale_price: $11.99
    title: Shantae and the Pirate's Curse
```
I just realized the README is not accurate, it's describing the sensor being for an individual game instead of a search term which can have multiple results.

I would have to think if there is a way around a search term matching multiple titles (or if there is a way to display a list of objects in the UI). 

The other route I could take is to not allow matching multiple titles and it would only ever match the first result if there were multiple.  This would require the wishlist to have very specific titles like `Shantae: Half-Genie Hero Ultimate Edition` and `Shantae and the Pirate's Curse` instead of `Shantae`.

Open to your thoughts!  Right now I"m leaning toward the latter option.  Releasing a new major version that breaks backwards compatibility and each search term sensor would become a binary sensor like you mentioned.  Then explicitly state in the README that you must enter the *exact full title* for it to work.
